antigen use oh-my-zsh

antigen bundle git
antigen bundle nvm
zstyle ':omz:plugins:nvm' autoload yes
zstyle ':omz:plugins:nvm' silent-autoload yes # optionally remove the output generated by NVM when autoloading
antigen bundle zoxide
antigen bundle fzf
antigen bundle jenv

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-docker
antigen bundle Aloxaf/fzf-tab

antigen theme robbyrussell

antigen apply
