backend = "glx";
blur_method = "dual_kawase";
blur_deviation = true;

blur-background = true;

corner-radius = 4;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

shadow = true;

inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;

fading = true;
fade-delta = 2;
